//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer_Device_Services
    {
        public int cds_key { get; set; }
        public int cds_service_key { get; set; }
        public int cds_device_key { get; set; }
    
        public virtual mbshop_device_detail mbshop_device_detail { get; set; }
        public virtual mbshop_service_detail mbshop_service_detail { get; set; }
    }
}
