//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mb_device_images
    {
        public int image_key { get; set; }
        public string image_path { get; set; }
        public int device_id { get; set; }
    
        public virtual mbshop_device_detail mbshop_device_detail { get; set; }
    }
}
