//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbshop_device_detail
    {
        public int device_key { get; set; }
        public string device_serial_number { get; set; }
        public string device_imei_number_1 { get; set; }
        public string device_imei_number_2 { get; set; }
        public int device_model_key { get; set; }
        public int device_fault_key { get; set; }
        public System.DateTime device_date_submitt { get; set; }
        public string device_description { get; set; }
        public byte[] device_condition_image { get; set; }
    
        public virtual mb_fault_detail mb_fault_detail { get; set; }
        public virtual mb_model_detail mb_model_detail { get; set; }
    }
}
