//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOBILESHOPEntities : DbContext
    {
        public MOBILESHOPEntities()
            : base("name=MOBILESHOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<mb_brand_detail> mb_brand_detail { get; set; }
        public virtual DbSet<mb_device_images> mb_device_images { get; set; }
        public virtual DbSet<mb_fault_detail> mb_fault_detail { get; set; }
        public virtual DbSet<mb_model_detail> mb_model_detail { get; set; }
        public virtual DbSet<mbshop_customer_details> mbshop_customer_details { get; set; }
        public virtual DbSet<mbshop_device_detail> mbshop_device_detail { get; set; }
    }
}
